language: python
python:
- 3.6

env:
  matrix:
    - TEST=tests/test_notebooks.py

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/anaconda/bin:$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda env create -f environment.yml
  - source activate gwb-dc
  - export MPLBACKEND="agg"
  - conda install pytest
  - pip install testipynb

script:
  - travis_wait 45 pytest $TEST -v -s
